import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.LinkedHashMap;
import java.util.Map;
//import com.fasterxml.jackson.dataformat.yaml.

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// https://dzone.com/articles/read-yaml-in-java-with-jackson
public class App {

  private String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    // http://blog.pepese.com/entry/20130915/1379222428
    String input = "{\"address\":\"Yokohama\",\"id\":\"4\",\"name\":\"Takahashi\"}";

    // JSON -> Map
    Map<String, String> map = new LinkedHashMap<>();
    ObjectMapper mapper = new ObjectMapper();
    try {
      map = mapper.readValue(input, new TypeReference<LinkedHashMap<String, String>>() {
      });
      System.out.println(map);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
